import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
function extractKey(raw: string | undefined, prefixes: string[]): string | null {
  if (!raw) return null;
  if (prefixes.some((p) => raw.startsWith(p)) || raw.split(".").length === 3) return raw;
  try {
    const parsed = JSON.parse(raw);
    const walk = (value: unknown): string | null => {
      if (typeof value === "string" && (prefixes.some((p) => value.startsWith(p)) || value.split(".").length === 3)) return value;
      if (Array.isArray(value)) for (const item of value) { const found = walk(item); if (found) return found; }
      if (value && typeof value === "object") for (const item of Object.values(value as Record<string, unknown>)) { const found = walk(item); if (found) return found; }
      return null;
    };
    return walk(parsed);
  } catch { return null; }
}
const PUBLISHABLE_KEY = extractKey(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS"), ["sb_publishable_"]) ?? extractKey(Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), ["sb_publishable_"]) ?? extractKey(Deno.env.get("SUPABASE_ANON_KEY"), ["eyJ"]) ?? "";
const SERVICE_KEY = extractKey(Deno.env.get("SUPABASE_SECRET_KEYS"), ["sb_secret_"]) ?? extractKey(Deno.env.get("SUPABASE_SECRET_KEY"), ["sb_secret_"]) ?? extractKey(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"), ["eyJ"]) ?? "";
const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-smartos-runner-token","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json","Cache-Control":"no-store"};
const SAFE_ID=/^[A-Za-z0-9._:-]+$/; const SHA=/^sha256:[0-9a-f]{64}$/i;
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:cors});}
async function sha256(value:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return "sha256:"+[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function serviceHeaders(extra:Record<string,string>={}){const h:Record<string,string>={apikey:SERVICE_KEY,"Content-Type":"application/json",...extra};if(SERVICE_KEY.split(".").length===3)h.Authorization=`Bearer ${SERVICE_KEY}`;return h;}
async function rest(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{...serviceHeaders(),...(init.headers as Record<string,string>??{})}});}
async function getUser(req:Request){const auth=req.headers.get("authorization")??"";if(!auth.toLowerCase().startsWith("bearer ")||!PUBLISHABLE_KEY)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:PUBLISHABLE_KEY,Authorization:auth}});if(!r.ok)return null;const d=await r.json();return d?.id?{id:d.id}:null;}
async function runnerCredential(req:Request,runnerId:string){const token=req.headers.get("x-smartos-runner-token")??"";if(!SAFE_ID.test(runnerId)||token.length<32)return null;const hash=await sha256(token);const now=new Date().toISOString();const q=new URLSearchParams({runner_id:`eq.${runnerId}`,credential_hash:`eq.${hash}`,revoked_at:"is.null",expires_at:`gt.${now}`,select:"credential_id,enrollment_id,expires_at"});const r=await rest(`smart_os_runner_credentials?${q}`);return r.ok?(await r.json())[0]??null:null;}
function hasFullToolchain(lane:string,row:any){const tools=new Set(Array.isArray(row.tools)?row.tools.map(String):[]);if(lane==="android")return (tools.has("gradle")||tools.has("./gradlew"))&&tools.has("jarsigner");return row.host_platform==="macos"&&tools.has("xcodebuild")&&tools.has("security");}
async function availableRunner(lane:string,requestedRunnerId?:string){const now=Date.now();const q=new URLSearchParams({lane:`eq.${lane}`,state:"eq.available",select:"attestation_id,runner_id,lane,host_platform,tools,provider_handle_id,state,expires_at,last_heartbeat_at,public_publish_authorized,store_upload_authorized"});if(requestedRunnerId)q.set("runner_id",`eq.${requestedRunnerId}`);const r=await rest(`smart_os_signing_runner_attestations?${q}`);if(!r.ok)throw new Error("runner lookup failed");const rows=await r.json();return rows.find((row:any)=>row.public_publish_authorized===false&&row.store_upload_authorized===false&&row.last_heartbeat_at&&now-Date.parse(row.last_heartbeat_at)<=600000&&Date.parse(row.expires_at)>now&&hasFullToolchain(lane,row))??null;}
async function provider(handleId:string){const q=new URLSearchParams({handle_id:`eq.${handleId}`,verification:"eq.verified",exposes_secret_values:"eq.false",select:"handle_id,lane,provider,required_secret_refs,verification,exposes_secret_values"});const r=await rest(`smart_os_signing_provider_handles?${q}`);if(!r.ok)throw new Error("provider lookup failed");return (await r.json())[0]??null;}
function commandFor(lane:string,projectId:string){return lane==="android"?{command:{executable:"smart-os-sign-android",args:[`workspaces/${projectId}/build/android`],workingDirectory:"."},outputPath:`workspaces/${projectId}/build/android/app/build/outputs/bundle/release/app-release.aab`}:{command:{executable:"smart-os-sign-ios",args:[`workspaces/${projectId}/build/ios`],workingDirectory:"."},outputPath:`workspaces/${projectId}/build/ios/build/SmartOS.xcarchive`};}
async function issueJob(req:Request,body:any){
  const user=await getUser(req);if(!user)return json(401,{error:"authenticated SMART OS user required"});
  const releaseCandidateId=String(body.releaseCandidateId??"");const lane=String(body.lane??"");const requestedRunnerId=body.runnerId?String(body.runnerId):undefined;
  if(!/^[0-9a-f-]{36}$/i.test(releaseCandidateId)||!["android","ios"].includes(lane)||(requestedRunnerId&&!SAFE_ID.test(requestedRunnerId)))return json(400,{error:"invalid signing job scope"});
  const q=new URLSearchParams({release_candidate_id:`eq.${releaseCandidateId}`,status:"eq.promoted",public_publish_authorized:"eq.false",select:"release_candidate_id,project_id,version,candidate_fingerprint,approval_request_id,approved_by,target_lanes,status,public_publish_authorized"});const cr=await rest(`smart_os_release_candidates?${q}`);if(!cr.ok)return json(500,{error:"release candidate lookup failed"});const c=(await cr.json())[0];
  if(!c||c.approved_by!==user.id||!Array.isArray(c.target_lanes)||!c.target_lanes.includes(lane)||!SHA.test(c.candidate_fingerprint))return json(403,{error:"release candidate is not approved for this user and lane"});
  const runner=await availableRunner(lane,requestedRunnerId);if(!runner)return json(409,{error:"no fresh available signing runner with complete toolchain for lane"});const p=await provider(runner.provider_handle_id);if(!p||p.lane!==lane)return json(409,{error:"runner signing provider is not verified"});
  const spec=commandFor(lane,c.project_id);const payload={release_candidate_id:c.release_candidate_id,project_id:c.project_id,version:c.version,candidate_fingerprint:c.candidate_fingerprint,lane,runner_id:runner.runner_id,provider_handle_id:runner.provider_handle_id,command:spec.command,output_path:spec.outputPath,secret_refs:Array.isArray(p.required_secret_refs)?p.required_secret_refs:[],status:"queued",created_by:user.id,public_publish_authorized:false,store_upload_authorized:false};
  const r=await rest("smart_os_signing_jobs",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)});if(r.status===409)return json(409,{error:"an active signing job already exists for this release candidate lane"});if(!r.ok)return json(500,{error:"signing job issuance failed"});const job=(await r.json())[0];return json(200,{jobId:job.job_id,releaseCandidateId:job.release_candidate_id,lane:job.lane,runnerId:job.runner_id,status:job.status,outputPath:job.output_path,secretRefs:job.secret_refs,publicPublishAuthorized:false,storeUploadAuthorized:false});
}
async function nextJob(req:Request,body:any){const runnerId=String(body.runnerId??"");if(!await runnerCredential(req,runnerId))return json(401,{error:"valid runner credential required"});const now=new Date();await rest(`smart_os_signing_jobs?runner_id=eq.${encodeURIComponent(runnerId)}&status=eq.leased&lease_expires_at=lt.${encodeURIComponent(now.toISOString())}`,{method:"PATCH",body:JSON.stringify({status:"queued",leased_at:null,lease_expires_at:null})});const q=new URLSearchParams({runner_id:`eq.${runnerId}`,status:"eq.queued",select:"job_id,release_candidate_id,project_id,version,candidate_fingerprint,lane,runner_id,provider_handle_id,command,output_path,secret_refs,status,created_at",order:"created_at.asc",limit:"1"});const r=await rest(`smart_os_signing_jobs?${q}`);if(!r.ok)return json(500,{error:"job queue lookup failed"});const job=(await r.json())[0];if(!job)return json(200,{noJob:true,publicPublishAuthorized:false,storeUploadAuthorized:false});const leaseExpiresAt=new Date(Date.now()+600000).toISOString();const p=await rest(`smart_os_signing_jobs?job_id=eq.${job.job_id}&status=eq.queued`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"leased",leased_at:now.toISOString(),lease_expires_at:leaseExpiresAt})});if(!p.ok||(await p.json()).length!==1)return json(409,{error:"job was leased concurrently"});return json(200,{...job,status:"leased",leaseExpiresAt,publicPublishAuthorized:false,storeUploadAuthorized:false});}
async function completeJob(req:Request,body:any){const runnerId=String(body.runnerId??"");const jobId=String(body.jobId??"");const result=String(body.result??"");const artifactSha256=body.artifactSha256?String(body.artifactSha256):null;const artifactSizeBytes=Number.isFinite(Number(body.artifactSizeBytes))?Number(body.artifactSizeBytes):null;const resultSummary=String(body.resultSummary??"").slice(0,1000);if(!await runnerCredential(req,runnerId))return json(401,{error:"valid runner credential required"});if(!/^[0-9a-f-]{36}$/i.test(jobId)||!["succeeded","failed"].includes(result))return json(400,{error:"invalid signing completion"});if(result==="succeeded"&&(!artifactSha256||!SHA.test(artifactSha256)||artifactSizeBytes===null||artifactSizeBytes<0))return json(400,{error:"successful signing completion requires artifact digest and size"});const now=new Date().toISOString();const p=await rest(`smart_os_signing_jobs?job_id=eq.${jobId}&runner_id=eq.${encodeURIComponent(runnerId)}&status=eq.leased&lease_expires_at=gt.${encodeURIComponent(now)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:result,completed_at:now,artifact_sha256:artifactSha256,artifact_size_bytes:artifactSizeBytes,result_summary:resultSummary})});if(!p.ok)return json(500,{error:"signing completion update failed"});const u=(await p.json())[0];if(!u)return json(409,{error:"signing job lease is invalid or expired"});return json(200,{jobId:u.job_id,status:u.status,artifactSha256:u.artifact_sha256,artifactSizeBytes:u.artifact_size_bytes,publicPublishAuthorized:false,storeUploadAuthorized:false});}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(!SUPABASE_URL||!PUBLISHABLE_KEY||!SERVICE_KEY)return json(503,{error:"signing jobs gateway environment is incomplete"});try{const body=await req.json().catch(()=>({}));const action=String(body.action??"");if(action==="issue-job")return await issueJob(req,body);if(action==="next-job")return await nextJob(req,body);if(action==="complete-job")return await completeJob(req,body);return json(400,{error:"unsupported signing job action"});}catch(error){console.error("smart-os-signing-jobs error",error instanceof Error?error.message:"unknown");return json(500,{error:"signing jobs gateway internal error"});}});
