import type { ImplementationBundle, ImplementationRequest } from "./types";

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export function generateImplementation(request: ImplementationRequest): ImplementationBundle {
  const templateId = request.domain === "game" ? "web-game-minimal" : "web-app-minimal";
  const files = [
    {
      path: "project.json",
      content: json({
        projectId: request.projectId,
        title: request.title,
        domain: request.domain,
        targetPlatforms: request.targetPlatforms,
        requirements: request.requirements,
      }),
    },
    {
      path: "README.md",
      content: `# ${request.title}\n\nGenerated by SMART OS inside an isolated workspace.\n`,
    },
  ];

  if (request.domain === "game") {
    files.push(
      {
        path: "index.html",
        content: "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>SMART OS Game</title></head><body><canvas id=\"game\" width=\"360\" height=\"640\"></canvas><script type=\"module\" src=\"./src/main.js\"></script></body></html>\n",
      },
      {
        path: "src/main.js",
        content: "const canvas=document.querySelector('#game');const ctx=canvas.getContext('2d');ctx.fillStyle='#111';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#fff';ctx.font='20px sans-serif';ctx.fillText('SMART OS prototype',70,320);\n",
      },
    );
  }

  return { projectId: request.projectId, templateId, files, requiresExternalExecution: false };
}
